apiVersion: apps/v1
kind: Deployment
metadata:
    name: appppy-deployment
    namespace: default
    labels:
        app: appppy
spec:
    replicas: 2
    selector:
        matchLabels:
            app: appppy
    template:
        metadata:
            labels:
                app: appppy
        spec:
            containers:
                - name: appppy
                  image: pacman212/appy:v1
                  ports:
                      - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
    name: appppy-service
    namespace: default
spec:
    selector:
        app: appppy
    ports:
        - protocol: TCP
          port: 80
          targetPort: 5000
    type: LoadBalancer
